set(freertos_cm4_src
    ${freertos_dir}/portable/GCC/ARM_CM4F/port.c
    ${freertos_dir}/portable/MemMang/heap_1.c
    ${freertos_dir}/portable/MemMang/heap_2.c
    ${freertos_dir}/portable/MemMang/heap_3.c
    ${freertos_dir}/portable/MemMang/heap_4.c
    ${freertos_dir}/portable/MemMang/heap_5.c
    ${freertos_dir}/croutine.c
    ${freertos_dir}/event_groups.c
    ${freertos_dir}/list.c
    ${freertos_dir}/queue.c
    ${freertos_dir}/stream_buffer.c
    ${freertos_dir}/tasks.c
    ${freertos_dir}/timers.c
)

set(freertos_cm4_inc
    ${freertos_dir}/include/atomic.h
    ${freertos_dir}/include/croutine.h
    ${freertos_dir}/include/deprecated_definitions.h
    ${freertos_dir}/include/event_groups.h
    ${freertos_dir}/include/FreeRTOSConfig_template.h
    ${freertos_dir}/include/FreeRTOS.h
    ${freertos_dir}/include/list.h
    ${freertos_dir}/include/message_buffer.h
    ${freertos_dir}/include/mpu_prototypes.h
    ${freertos_dir}/include/mpu_wrappers.h
    ${freertos_dir}/include/portable.h
    ${freertos_dir}/include/projdefs.h
    ${freertos_dir}/include/queue.h
    ${freertos_dir}/include/semphr.h
    ${freertos_dir}/include/stack_macros.h
    ${freertos_dir}/include/StackMacros.h
    ${freertos_dir}/include/stdint.readme
    ${freertos_dir}/include/stream_buffer.h
    ${freertos_dir}/include/task.h
    ${freertos_dir}/include/timers.h
    ${freertos_dir}/portable/GCC/ARM_CM4F/portmacro.h
)