set(stm32wbxx_hal_src
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_adc.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_adc_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_comp.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_cortex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_crc.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_crc_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_cryp.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_cryp_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_dma.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_dma_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_exti.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_flash.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_flash_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_gpio.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_hsem.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_i2c.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_i2c_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_ipcc.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_irda.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_iwdg.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_lcd.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_lptim.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_pcd.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_pcd_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_pka.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_pwr.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_pwr_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_qspi.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_rcc.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_rcc_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_rng.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_rtc.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_rtc_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_sai.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_sai_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_smartcard.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_smartcard_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_smbus.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_smbus_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_spi.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_spi_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_tim.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_tim_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_tsc.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_uart.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_uart_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_usart.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_usart_ex.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_hal_wwdg.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_adc.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_comp.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_crc.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_crs.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_dma.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_exti.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_gpio.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_i2c.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_lptim.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_lpuart.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_pka.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_pwr.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_rcc.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_rng.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_rtc.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_spi.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_tim.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_usart.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_usb.c
    ${stm32wbxx_hal_dir}/Src/stm32wbxx_ll_utils.c
)

set(stm32wbxx_hal_inc
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_adc_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_adc.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_comp.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_cortex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_crc_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_crc.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_cryp_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_cryp.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_def.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_dma_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_dma.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_exti.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_flash_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_flash.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_gpio_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_gpio.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_hsem.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_i2c_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_i2c.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_ipcc.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_irda_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_irda.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_iwdg.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_lcd.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_lptim.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_pcd_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_pcd.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_pka.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_pwr_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_pwr.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_qspi.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_rcc_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_rcc.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_rng.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_rtc_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_rtc.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_sai_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_sai.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_smartcard_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_smartcard.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_smbus_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_smbus.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_spi_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_spi.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_tim_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_tim.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_tsc.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_uart_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_uart.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_usart_ex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_usart.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_hal_wwdg.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_adc.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_bus.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_comp.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_cortex.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_crc.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_crs.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_dma.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_dmamux.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_exti.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_gpio.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_hsem.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_i2c.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_ipcc.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_iwdg.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_lptim.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_lpuart.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_pka.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_pwr.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_rcc.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_rng.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_rtc.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_spi.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_system.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_tim.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_usart.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_usb.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_utils.h
    ${stm32wbxx_hal_dir}/Inc/stm32wbxx_ll_wwdg.h
)