theme: jekyll-theme-minimal
title: STEP Hardware Repository
description: The monorepository for Social Tech Enterprise with Purpose (STEP). A class at <a href="https://www.olin.edu/">Olin College of Engineering</a>.
