theme: jekyll-theme-minimal
title: STEP Hardware Repository
description: |
  The monorepository for Social Tech Enterprise with Purpose (STEP).
  A class at [Olin College of Engineering](https://www.olin.edu/).
